# Generated by Django 2.2.6 on 2019-10-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20191010_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('BUG', 'Bug'), ('FEATURE', 'Feature'), ('MAINTENANCE', 'Maintenance')], max_length=32),
        ),
    ]
