# Generated by Django 2.2.6 on 2019-10-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20191010_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='started',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
