# Generated by Django 2.2.6 on 2019-10-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_auto_20191010_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ticket.TicketCollection'),
            preserve_default=False,
        ),
    ]
